import type { PipelineDefinition } from "../types/pipeline";

/**
 * Sanitize a string to be a valid Nextflow process identifier.
 * Replaces non-alphanumeric characters with underscores.
 */
function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1");
}

/**
 * Generate a Nextflow DSL2 script from a PipelineDefinition.
 */
export function generateNextflowScript(
  pipeline: PipelineDefinition,
  sourceId: string
): string {
  const source = pipeline.sources.find((s) => s.id === sourceId);
  if (!source || source.steps.length === 0) {
    return "// No source or steps found for the selected pipeline.\n";
  }

  const version = pipeline.version || "0.1.0";
  const processIds: string[] = [];

  let script = "#!/usr/bin/env nextflow\n\n";
  script += "nextflow.enable.dsl=2\n\n";

  // Header comment
  script += "/*\n";
  script += ` * Generated by FlowSeq\n`;
  script += ` * Pipeline: ${pipeline.name} (${pipeline.nameZH})\n`;
  script += ` * Source: ${source.name} (${source.id})\n`;
  script += ` * Version: ${version}\n`;
  script += ` * Date: ${new Date().toISOString().split("T")[0]}\n`;
  script += " *\n";
  script += " * This is a skeleton template. Each process script block contains\n";
  script += " * tool name + parameter comments as a starting point.\n";
  script += " * Review and customize before running.\n";
  script += " */\n\n";

  // Params section
  script += "/* ─── Parameters ─── */\n";
  script += "params {\n";
  script += "  input_dir  = \"data/raw\"\n";
  script += "  output_dir = \"results\"\n";
  script += "}\n\n";

  // Generate process definitions
  script += "/* ─── Processes ─── */\n\n";
  for (const step of source.steps) {
    const processName = sanitizeId(step.id);
    processIds.push(processName);

    script += `process ${processName.toUpperCase()} {\n`;
    if (step.tools.length > 0 && step.tools[0].docker) {
      script += `    container "${step.tools[0].docker}"\n`;
    }
    script += `    publishDir "\${params.output_dir}/${processName}", mode: 'copy'\n\n`;
    script += `    input:\n`;
    script += `    path input_data\n\n`;
    script += `    output:\n`;
    script += `    path "output/*", emit: results\n\n`;
    script += `    script:\n`;
    script += `    """\n`;
    script += `    # ${step.name}\n`;
    script += `    # ${step.description}\n`;

    for (const tool of step.tools) {
      const paramsStr = tool.params ? ` ${tool.params}` : "";
      script += `    # Tool: ${tool.name} (v${tool.version}): ${tool.name}${paramsStr}\n`;
    }

    if (step.notes) {
      script += `    # Notes: ${step.notes}\n`;
    }

    script += `    """\n`;
    script += `}\n\n`;
  }

  // Workflow section
  script += "/* ─── Workflow ─── */\n\n";
  script += "workflow {\n";
  script += "    // Input channel: point to your FASTQ / BAM / VCF files\n";
  script += `    Channel\n`;
  script += `        .fromPath("\${params.input_dir}/*")\n`;
  script += `        .set { input_ch }\n\n`;

  let prevOutput = "input_ch";
  for (let i = 0; i < processIds.length; i++) {
    const procId = processIds[i];
    script += `    ${procId.toUpperCase()}(\n`;
    script += `        ${prevOutput}\n`;
    script += `    )\n`;

    if (i < processIds.length - 1) {
      script += `    ${procId.toUpperCase()}.out.results\n`;
      script += `        .set { ${procId}_ch }\n\n`;
      prevOutput = `${procId}_ch`;
    } else {
      script += `\n`;
    }
  }

  script += `    // Uncomment below to collect final results\n`;
  script += `    // ${processIds[processIds.length - 1].toUpperCase()}.out.results\n`;
  script += `    //     .collectFile(name: 'summary.txt', storeDir: "\${params.output_dir}")\n`;
  script += `}\n`;

  return script;
}
